### PR TITLE
Kessler physics computes a consistent relative humidity

### LINKED ISSUE #17: Kessler physics needs to compute relative humidity
Kessler needs to produce the relative humidity instead of having it computed in cam_diagnostics. This guarantees that the maximum relative humidity is 100%.

### PR DESCRIPTION
**Pull request by cjablono**
Instead of computing the relative humidity in cam_diagnostics, the relative humidity is now computed in the Kessler routine. This is now consistent with the computation of the vapor saturation value, and produces a maximum relative humidity of 100%.
Fixes #17

### CODE REVIEW

**Comment by gold2718** [comment]
Yes, the CESM2.2 release is the priority, however, the PR branch _should_ also work as-is in CAMDEN. Let me know if it does not.

**Comment by cacraigucar** [comment]
For a 9 timestep FKESSLER run using the cam_development branch, I am seeing identical answers to the prior version.  I assume that this is possible.  @gold2718 What testing do we want to make to validate this change in CAM?

**Comment by gold2718** [comment]
@cjablono, any idea what would be a good test to make sure we have the fix plugged in correctly? Is there a test case that exercises the issue and would show a difference?

**Comment by gold2718** [comment]
@brian-eaton, can you have a look at this so we can get it in and tag it? We need the updated tag to finish the Simpler Models PR.

**Comment by cacraigucar** [comment]
This has now been tagged version0_0_006

**Pull request merged**
